### ISSUE TITLE
ZkLend protocol question

### ISSUE THREAD

**Issue by HenriBrg** [zkLend/zklend-v1-core#72]
Hi Zk Lend team !

I'd like to ask you 3 questions if I may (I was redirected here following questions on Discord)
1. Are positions liquidated on the basis of HF with borrow_factor or without borrow_factor?
2. We only see a very small amount of liquidation on the chain (<10$), is there a maximum amount of liquidation debt? Because if we just reset the HF to 1,000, it will be liquidated directly afterwards ..
3. There is a get_user_flags function, what are the user flags used for / what do they mean ? (no mention in the doc).

Thank you for your attention.

**Comment by xJonathanLEI** [comment]
1. _Are positions liquidated on the basis of HF with borrow_factor or without borrow_factor?_

   Without. `borrow_factor` is only applied when taking out loans. The collateralization check `liquidate` ignores it. See this code section:

   https://github.com/zkLend/zklend-v1-core/blob/cd08ab95109a561097cb18d424a7ac13ca25bbbf/src/market/internal.cairo#L310-L311

   where the `apply_borrow_factor` argument is set to `false`.

2. _We only see a very small amount of liquidation on the chain (<10$), is there a maximum amount of liquidation debt? Because if we just reset the HF to 1,000, it will be liquidated directly afterwards .._

   Currently the zkLend team runs a liquidator that's rather aggressive: it's configured to liquidate any positions with bad debt greater than 10 USD I believe. The reason you're seeing small amounts is because they get liquidated before they become big enough. Liquidations in zkLend is progressive unlike some other lending protocols - instead of liquidating a certain % of the user's position, you're only allowed to liquidate up to the amount it takes to bring it back to a healthy state.

   I don't understand the "reset the HF to 1,000" part. How do you reset? Also `HF >= 1` means healthy, so an HF of 1,000 definitely won't get you liquidated.

3. _There is a get_user_flags function, what are the user flags used for / what do they mean ? (no mention in the doc)._

   It's a gas optimization bitmap that contains big flags that indicate whether a user uses any token as collateral or has debt. You can check the details in the code here:

   https://github.com/zkLend/zklend-v1-core/blob/cd08ab95109a561097cb18d424a7ac13ca25bbbf/src/market.cairo#L29-L34

**Comment by HenriBrg** [comment]
Thanks a lot! @xJonathanLEI 
For 1) and 3), alright, duly noted.

For the 2nd question, my bad, let me reformulate.
I was trying to understand how is defined the debt amount repaid, does it have to be a precise amount that, once repaid, set the new HF to a minimum target HF (like 1.5 / 150%, or 1.25 etc) or is it just enough if the HF is > 1.0 / 100%, like 1.000000..0001 (slightly above 1)

Again, thanks for the help.

**Comment by xJonathanLEI** [comment]
I believe there's a misconception here. No, you _cannot_ liquidate a user such that their health factor goes _above_ 1. The best you can do is to liquidate so much that it gets to exactly equal to 1. Will the user be subject to more liquidations right after? Yes, and actually immediately if the first liquidation didn't even bring the position to 1. But does it matter how many separate liquidations a position goes through? Not really.

**Comment by HenriBrg** [comment]
Indeed, I was just surprised to see that the liquidation target HF is only 1, which incentivise a chain of liquidations for a same position.

Okay, so if I recap the approach took by ZkLend (and the expected behavior of liquidation bot), it's that user get their positions liquidated when HF < 1.0, and after liquidation, the new HF is == 1.0.
As a result, the amount of debt liquidated is very low (a few dozen dollars), which create a very low incentive to liquidate.

**Theoretically, can we see the liquidation of a very small amount of debt, with the bonus on the collateral equivalent just covering the gas cost ?**

Thank you !

**Comment by xJonathanLEI** [comment]
Sorry but again I don't think I fully understand the question here. You could in theory liquidate any amount that might not even cover the gas cost (irrational though). The target HF is indeed 1, as we believe this is the most fair to users (not ruling out changing this in the future though, as it does impose some risks to the protocol). Also, we expect the gas cost of Starknet to continue to drop and eventually reach a point where liquidating very small amounts is worth it.

As a liquidator, you do need to take into account all your costs to consider whether a liquidation opportunity is wroth it, regardless of what the HF target is.

**Comment by HenriBrg** [comment]
Okay, I can now see the overall reason why the target HF is 1
Sorry for the lack of clarity, it's not always easy to formulate the question exactly in this kind of subject, but your answer answered it
Thank you very much for helping us to understand zkLend better!

**Comment by xJonathanLEI** [comment]
No problem. Glad that I was able to help.
